# Navigation Parameters for Nav2

# This file contains configuration parameters for the Nav2 navigation system.

# Basic parameters
controller_server:
  ros__parameters:
    use_sim_time: false
    publish_rate: 10.0
    max_velocity: 0.5
    min_velocity: 0.1
    max_acceleration: 0.5
    min_acceleration: 0.1

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_frequency: 1.0
    max_planning_time: 2.0
    goal_tolerance: 0.1

costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      robot_base_frame: "base_footprint"
      update_frequency: 5.0
      publish_frequency: 5.0
      static_map: true
      rolling_window: true
      width: 10.0
      height: 10.0
      resolution: 0.05

  local_costmap:
    ros__parameters:
      use_sim_time: false
      robot_base_frame: "base_footprint"
      update_frequency: 5.0
      publish_frequency: 5.0
      static_map: false
      rolling_window: true
      width: 5.0
      height: 5.0
      resolution: 0.05

# Recovery behaviors
recovery_server:
  ros__parameters:
    use_sim_time: false
    recovery_behavior: ["rotate_recovery", "clear_costmap_recovery"]