# oakd_params.yaml — OAK-D Pro config for RGBD + VSLAM on USB 2.0
# Bandwidth budget: ~31.5 MB/s (USB 2.0 with double hub, ~30 MB/s capacity)
#
# Streams:
#   RGB  480P@15fps MJPEG q50  (~0.7 MB/s)
#   Depth 400P@30fps raw       (~15.4 MB/s)
#   Stereo L/R rect 400P@30fps (~15.4 MB/s)
#   IMU                        (~0.01 MB/s)
#
# WARNING: Do NOT use CLI parameter overrides (key:=value) with camera.launch.py.
# They are silently ignored. All parameters must be in this YAML file.
#
/oak:
  ros__parameters:
    camera:
      i_pipeline_type: RGBD
      i_usb_speed: "HIGH"          # USB 2.0 (480 Mbps) — matches physical bus
      i_enable_imu: true            # BMI270 IMU for VSLAM fusion
      i_enable_ir: false            # IR OFF — dots create false VSLAM features
      i_nn_type: none               # Disable NN to save MyriadX resources
    rgb:
      i_resolution: "480P"          # 640x480 — smallest useful for LLM vision
      i_fps: 15.0                   # Reduced fps to save bandwidth for stereo
      i_low_bandwidth: true         # MJPEG compression on-chip
      i_low_bandwidth_quality: 50   # MJPEG quality (10:1 compression)
    left:
      i_resolution: "400"           # 640x400 — matches isaac_vslam.yaml
      i_fps: 30.0                   # 30fps = VSLAM minimum requirement
    right:
      i_resolution: "400"           # Must match left
      i_fps: 30.0                   # Must match left
    stereo:
      i_publish_synced_rect_pair: true    # HW-synced rectified L/R for VSLAM
      i_reverse_stereo_socket_order: true # OAK-D Pro socket order
      i_output_disparity: true            # Keep depth output for Nav2
      i_low_bandwidth: false              # RAW required — MJPEG corrupts VSLAM
